### ISSUE TITLE
Create application loading issue 

### ISSUE THREAD

**Issue by jubisha** [Templar-Payments/Templar_Payments_BugTracking#100]
User name - kojoye1977@biohorta.com
Paswd - 123

enter the company number and hit search, it takes very very very long to pull the results.
seems like a performance issue

<img width="1125" alt="Screenshot 2021-07-29 at 5 03 57 PM" src="https://user-images.githubusercontent.com/56086942/127485390-75462bca-cd3b-468d-a871-0fa96fbd43f8.png">

**Comment by NathanLeadill** [comment]
You haven't entered a name properly and so it's taking the system longer to find the company.
