### ISSUE TITLE
Messaging Centre: AWS link do not appear as Hyperlinks, no links appear as hyperlinks

### ISSUE THREAD

**Issue by nathanwatkinstemplar** [Templar-Payments/Templar_Payments_BugTracking#105]
You also need to add text when adding a file before it lets you send that file

https://share.vidyard.com/watch/Cax68WtJm8sGmFhLhmDMnt?

**Comment by NathanLeadill** [comment]
Yeah this is actually a REALLY REALLY hard thing to do, and theres not an easy way i can think. We're storing the link as a string, so when we send that to the FE there's no way for it to know that string is a link and to parse that to the right HTML. Dunno how we'd get around this i assumed people could copy and paste a link for now :/

**Comment by NathanLeadill** [comment]
Spoke to nath about this gonna put on hold until we get twillio
