### ISSUE TITLE
Fill in manually empty fields issue

### ISSUE THREAD

**Issue by WilliamTemplar** [Templar-Payments/Templar_Payments_BugTracking#108]
When one or more mandatory fields are not completed, all mandatory fields display the error border. It should only appear for empty fields

<img width="945" alt="Screenshot 2021-07-30 at 09 27 50" src="https://user-images.githubusercontent.com/83643714/127630730-3c4fc97a-7a73-4621-9c0a-42840bbfce37.png">

**Comment by NathanLeadill** [comment]
https://user-images.githubusercontent.com/17186852/127775614-353e99b9-7328-45a6-8372-176082539a0b.mov

Fixed
