### ISSUE TITLE
Bug: Sent to merchant Link (I can split this into seperate bugs once Leadill has a goose

### ISSUE THREAD

**Issue by nathanwatkinstemplar** [Templar-Payments/Templar_Payments_BugTracking#109]
We tested this morning, me, Will and Dan but in order to video it may have had issues with cache as I've done it off of one machine. 

When you click send link to merchant, then pop-up says save to draft. Can we have this flick to Getstarted or even to Sales Dashboard?

The last two inputs (currency and e-com product are not avaliable on send to Merchant link

When we tested and when I've done it myself no notification is sent to the ISO sales user once completed

If you click messaging centre or ongoing app it breaks (did work on the video after a refresh)

It is not saving the draft so that the main ISO user can go back into it

If you submit once and then click the link again it doesn't recognise that data has already been filled and sent 

https://share.vidyard.com/watch/jx2vTj91nPQ8TD4ttpqFqz?

**Comment by NathanLeadill** [comment]
So when we send email to merchant we should set accountType as fillInManually. When the application is submitted then we change their accountType to merchant.

**Comment by NathanLeadill** [comment]
Fixed everything but.

The last two inputs (currency and e-com product are not avaliable on send to Merchant link
If you submit once and then click the link again it doesn't recognise that data has already been filled and sent

Work to fix this soon
