### ISSUE TITLE
Create Application - Fill the data manually 

### ISSUE THREAD

**Issue by jubisha** [Templar-Payments/Templar_Payments_BugTracking#11]
When you fill the data manually while creating the application and enter invalid email, company domain, it accepts, there are  no validations when the user inputs incorrect data 

<img width="1075" alt="Screenshot 2021-07-15 at 2 00 53 PM" src="https://user-images.githubusercontent.com/56086942/125756412-df3f7606-ba0f-4292-8447-dae730c1e3ba.png">.

**Comment by NathanLeadill** [comment]
Validations for this are too complicated to add into the current version, too much has been bolted on, needs a complete rewrite.
