### ISSUE TITLE
Send to Merchant: Links sends but then gets a status 500 error

### ISSUE THREAD

**Issue by nathanwatkinstemplar** [Templar-Payments/Templar_Payments_BugTracking#118]
https://share.vidyard.com/watch/vmaBGpAmmaFZtHb1HFZk85?

This is sending the links which works :-)

When I open the other link in Incognito, this happens. 

tracking.js:1 Uncaught (in promise) Error: License expired
    at tracking.js:1
    at async Promise.all (/application/merchant/index 0)
(anonymous) @ tracking.js:1
Promise.catch (async)
window.__lc_inited.reduce.Kt @ tracking.js:1
(anonymous) @ tracking.js:1
(anonymous) @ tracking.js:1
application.reducer.js:1110 {type: "@@redux/INIT9.e.8.4.s.g"}
application.reducer.js:1110 {type: "@@redux/PROBE_UNKNOWN_ACTION1.w.8.5.6.8"}
application.reducer.js:1110 {type: "@@redux/INIT9.e.8.4.s.g"}
application.reducer.js:1110 {type: "persist/PERSIST", register: ƒ, rehydrate: ƒ}
redux-logger.js:1  action persist/PERSIST @ 09:13:45.559
redux-logger.js:1  prev state {test: {…}, modal: {…}, user: {…}, application: {…}, organisation: {…}, …}
redux-logger.js:1  action     {type: "persist/PERSIST", register: ƒ, rehydrate: ƒ}
redux-logger.js:1  next state {test: {…}, modal: {…}, user: {…}, application: {…}, organisation: {…}, …}
application.reducer.js:1110 {type: "persist/REHYDRATE", payload: {…}, err: undefined, key: "root"}
redux-logger.js:1  action persist/REHYDRATE @ 09:13:45.619
redux-logger.js:1  prev state {test: {…}, modal: {…}, user: {…}, application: {…}, organisation: {…}, …}
redux-logger.js:1  action     {type: "persist/REHYDRATE", payload: {…}, err: undefined, key: "root"}
redux-logger.js:1  next state {test: {…}, modal: {…}, user: {…}, application: {…}, organisation: {…}, …}
App.js:40 {show: false, modalContent: {…}}
index.js:47 TOKEN eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Mjc5MTMzODEsImRhdGEiOnsiaWQiOiI2MTA3YTg0NGM2OTM1YjQ2Y2I4NmEyMWUiLCJ1c2VybmFtZSI6InRhbGtlZCB0b29tdWNoIiwicGVybWlzc2lvbnMiOltdLCJyb2xlIjoiZmlsbEluTWFudWFsIiwiY2hhbm5lbEFycmF5IjpbXSwiZW1haWwiOiJtZXJva28yMDIzQGZsaXBzc2wuY29tIiwiYXBwbGljYXRpb25JZCI6IjYxMDdhN2JhYzY5MzViNDZjYjg2YTIxNSJ9LCJpYXQiOjE2Mjc4OTE3ODF9._dpVifzJvD6NqZ8nqZTwMFNPrqgsqr1Ju8eoXZ7Mho8%20What%20is%20Disposable%20Temporary%20E-mail?%20Disposable%20email%20-%20is%20a%20free%20email%20service%20that%20allows%20to%20receive%20email%20at%20a%20temporary%20address%20that%20self-destructed%20after%20a%20certain%20time%20elapses.%20It%20is%20also%20known%20by%20names%20like%20:%20tempmail,%2010minutemail,%2010minmail,%20throwaway%20email,%20fake-mail%20,%20fake%20email%20generator,%20burner%20mail%20or%20trash-mail.%20Many%20forums,%20Wi-Fi%20owners,%20websites%20and%20blogs%20ask%20visitors%20to%20register%20before%20they%20can%20view%20content,%20post%20comments%20or%20download%20something.%20Temp-Mail%20-%20is%20most%20advanced%20throwaway%20email%20service%20that%20helps%20you%20avoid%20spam%20and%20stay%20safe.
index.js:47 TOKEN eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Mjc5MTMzODEsImRhdGEiOnsiaWQiOiI2MTA3YTg0NGM2OTM1YjQ2Y2I4NmEyMWUiLCJ1c2VybmFtZSI6InRhbGtlZCB0b29tdWNoIiwicGVybWlzc2lvbnMiOltdLCJyb2xlIjoiZmlsbEluTWFudWFsIiwiY2hhbm5lbEFycmF5IjpbXSwiZW1haWwiOiJtZXJva28yMDIzQGZsaXBzc2wuY29tIiwiYXBwbGljYXRpb25JZCI6IjYxMDdhN2JhYzY5MzViNDZjYjg2YTIxNSJ9LCJpYXQiOjE2Mjc4OTE3ODF9._dpVifzJvD6NqZ8nqZTwMFNPrqgsqr1Ju8eoXZ7Mho8%20What%20is%20Disposable%20Temporary%20E-mail?%20Disposable%20email%20-%20is%20a%20free%20email%20service%20that%20allows%20to%20receive%20email%20at%20a%20temporary%20address%20that%20self-destructed%20after%20a%20certain%20time%20elapses.%20It%20is%20also%20known%20by%20names%20like%20:%20tempmail,%2010minutemail,%2010minmail,%20throwaway%20email,%20fake-mail%20,%20fake%20email%20generator,%20burner%20mail%20or%20trash-mail.%20Many%20forums,%20Wi-Fi%20owners,%20websites%20and%20blogs%20ask%20visitors%20to%20register%20before%20they%20can%20view%20content,%20post%20comments%20or%20download%20something.%20Temp-Mail%20-%20is%20most%20advanced%20throwaway%20email%20service%20that%20helps%20you%20avoid%20spam%20and%20stay%20safe.
xhr.js:177 POST https://api.templarpayments.com/api/user/loginFromLink 500 (Internal Server Error)
(anonymous) @ xhr.js:177
e.exports @ xhr.js:13
e.exports @ dispatchRequest.js:50
Promise.then (async)
c.request @ Axios.js:61
(anonymous) @ bind.js:9
(anonymous) @ user.action.js:130
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
l @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ user.action.js:128
(anonymous) @ index.js:49
u @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
l @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ index.js:48
(anonymous) @ index.js:59
Tc @ react-dom.production.min.js:262
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ui @ react-dom.production.min.js:122
Cc @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:261
P @ scheduler.production.min.js:16
M.port1.onmessage @ scheduler.production.min.js:12
api.js:92 ERROR {"message":"Request failed with status code 500","name":"Error","stack":"Error: Request failed with status code 500\n    at e.exports (https://app.templarpayments.com/static/js/2.c2a576a5.chunk.js:2:807036)\n    at e.exports (https://app.templarpayments.com/static/js/2.c2a576a5.chunk.js:2:2129707)\n    at XMLHttpRequest.d.onreadystatechange (https://app.templarpayments.com/static/js/2.c2a576a5.chunk.js:2:805887)","config":{"url":"/user/loginFromLink","method":"post","data":"{\"token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Mjc5MTMzODEsImRhdGEiOnsiaWQiOiI2MTA3YTg0NGM2OTM1YjQ2Y2I4NmEyMWUiLCJ1c2VybmFtZSI6InRhbGtlZCB0b29tdWNoIiwicGVybWlzc2lvbnMiOltdLCJyb2xlIjoiZmlsbEluTWFudWFsIiwiY2hhbm5lbEFycmF5IjpbXSwiZW1haWwiOiJtZXJva28yMDIzQGZsaXBzc2wuY29tIiwiYXBwbGljYXRpb25JZCI6IjYxMDdhN2JhYzY5MzViNDZjYjg2YTIxNSJ9LCJpYXQiOjE2Mjc4OTE3ODF9._dpVifzJvD6NqZ8nqZTwMFNPrqgsqr1Ju8eoXZ7Mho8%20What%20is%20Disposable%20Temporary%20E-mail?%20Disposable%20email%20-%20is%20a%20free%20email%20service%20that%20allows%20to%20receive%20email%20at%20a%20temporary%20address%20that%20self-destructed%20after%20a%20certain%20time%20elapses.%20It%20is%20also%20known%20by%20names%20like%20:%20tempmail,%2010minutemail,%2010minmail,%20throwaway%20email,%20fake-mail%20,%20fake%20email%20generator,%20burner%20mail%20or%20trash-mail.%20Many%20forums,%20Wi-Fi%20owners,%20websites%20and%20blogs%20ask%20visitors%20to%20register%20before%20they%20can%20view%20content,%20post%20comments%20or%20download%20something.%20Temp-Mail%20-%20is%20most%20advanced%20throwaway%20email%20service%20that%20helps%20you%20avoid%20spam%20and%20stay%20safe.\"}","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8","authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Mjc5MTMyMDYsImRhdGEiOnsiaWQiOiI2MGY2ZTJmOTEyMzM4OTc4Nzk5NjMwNWUiLCJ1c2VybmFtZSI6IlRlbXBsYXIgUGF5bWVudHMgTHRkIiwicGVybWlzc2lvbnMiOltdLCJyb2xlIjoiYWRtaW4iLCJjaGFubmVsQXJyYXkiOlsiNjBmNTc1ZTI0YTg4ODY4MDE5ZTEzMWY2IiwiNjBmNzAwZjUzNTI5YWI3ZGNkZmIzNWJiIiwiNjBmNzAwZjUzNTI5YWI3ZGNkZmIzNWJjIiwiNjBmNzAwZjUzNTI5YWI3ZGNkZmIzNWJkIiwiNjBmNzA3ZDMzNTI5YWI3ZGNkZmIzNWQxIiwiNjBmNzA3ZDMzNTI5YWI3ZGNkZmIzNWQyIiwiNjBmNzA3ZDMzNTI5YWI3ZGNkZmIzNWQzIiwiNjBmN2UwYmEzNTI5YWI3ZGNkZmIzNWVjIiwiNjBmN2UwYmEzNTI5YWI3ZGNkZmIzNWVkIiwiNjBmODIwYTYzNTI5YWI3ZGNkZmIzNjk0IiwiNjBmODIwYTYzNTI5YWI3ZGNkZmIzNjk1IiwiNjBmODIwYTYzNTI5YWI3ZGNkZmIzNjk2IiwiNjBmODM3MWYzNTI5YWI3ZGNkZmIzNmUzIiwiNjBmODM3MWYzNTI5YWI3ZGNkZmIzNmU0IiwiNjBmODM3MWYzNTI5YWI3ZGNkZmIzNmU1IiwiNjBmOTU1NGRiZjYyYzQ0ZTZhYjVmNzFhIiwiNjBmOTU1NGRiZjYyYzQ0ZTZhYjVmNzFiIiwiNjBmOTU1NGRiZjYyYzQ0ZTZhYjVmNzFjIiwiNjBmYTdhYzdiZjYyYzQ0ZTZhYjVmNzgyIiwiNjBmYTdhYzdiZjYyYzQ0ZTZhYjVmNzgzIiwiNjBmYTdhYzdiZjYyYzQ0ZTZhYjVmNzg0IiwiNjBmYWM3MWZiZjYyYzQ0ZTZhYjVmN2E3IiwiNjBmYWM3MWZiZjYyYzQ0ZTZhYjVmN2E4IiwiNjBmYWM3MWZiZjYyYzQ0ZTZhYjVmN2E5IiwiNjBmZTgxZjhjYjQ5OWI0MDQ2MmJjYWM3IiwiNjBmZTgxZjhjYjQ5OWI0MDQ2MmJjYWM4IiwiNjBmZTgxZjhjYjQ5OWI0MDQ2MmJjYWM5IiwiNjEwMjhmZWU1YzlkNWE1NzEyZGFiNjE0IiwiNjEwMjhmZWU1YzlkNWE1NzEyZGFiNjE1IiwiNjEwMjhmZWU1YzlkNWE1NzEyZGFiNjE2IiwiNjEwMjhmZWU1YzlkNWE1NzEyZGFiNjE3IiwiNjEwMjlmNjQ1YzlkNWE1NzEyZGFiNjQzIiwiNjEwMjlmNjQ1YzlkNWE1NzEyZGFiNjQ0IiwiNjEwMjlmNjQ1YzlkNWE1NzEyZGFiNjQ1IiwiNjEwMjlmNjQ1YzlkNWE1NzEyZGFiNjQ2IiwiNjEwMmMzNTI1YzlkNWE1NzEyZGFiNjkzIl0sImVtYWlsIjoibmF0aGFuLndhdGtpbnNAdGVtcGxhcnBheW1lbnRzLmNvbSJ9LCJpYXQiOjE2Mjc4OTE2MDZ9.ZTh0hikR0GQ70IRSV1ViTsvcEvHNkV3rkgwDYOdiI38"},"baseURL":"https://api.templarpayments.com/api","transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1}}
index.js:50 POPEYE {error: Error: Request failed with status code 500
    at e.exports (https://app.templarpayments.com/static…}
application.reducer.js:1110 {type: "LOG_IN", payload: {…}}
redux-logger.js:1  action LOG_IN @ 09:13:45.805
redux-logger.js:1  prev state {test: {…}, modal: {…}, user: {…}, application: {…}, organisation: {…}, …}
redux-logger.js:1  action     {type: "LOG_IN", payload: {…}}
redux-logger.js:1  next state {test: {…}, modal: {…}, user: {…}, application: {…}, organisation: {…}, …}
index.js:47 TOKEN eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Mjc5MTMzODEsImRhdGEiOnsiaWQiOiI2MTA3YTg0NGM2OTM1YjQ2Y2I4NmEyMWUiLCJ1c2VybmFtZSI6InRhbGtlZCB0b29tdWNoIiwicGVybWlzc2lvbnMiOltdLCJyb2xlIjoiZmlsbEluTWFudWFsIiwiY2hhbm5lbEFycmF5IjpbXSwiZW1haWwiOiJtZXJva28yMDIzQGZsaXBzc2wuY29tIiwiYXBwbGljYXRpb25JZCI6IjYxMDdhN2JhYzY5MzViNDZjYjg2YTIxNSJ9LCJpYXQiOjE2Mjc4OTE3ODF9._dpVifzJvD6NqZ8nqZTwMFNPrqgsqr1Ju8eoXZ7Mho8%20What%20is%20Disposable%20Temporary%20E-mail?%20Disposable%20email%20-%20is%20a%20free%20email%20service%20that%20allows%20to%20receive%20email%20at%20a%20temporary%20address%20that%20self-destructed%20after%20a%20certain%20time%20elapses.%20It%20is%20also%20known%20by%20names%20like%20:%20tempmail,%2010minutemail,%2010minmail,%20throwaway%20email,%20fake-mail%20,%20fake%20email%20generator,%20burner%20mail%20or%20trash-mail.%20Many%20forums,%20Wi-Fi%20owners,%20websites%20and%20blogs%20ask%20visitors%20to%20register%20before%20they%20can%20view%20content,%20post%20comments%20or%20download%20something.%20Temp-Mail%20-%20is%20most%20advanced%20throwaway%20email%20service%20that%20helps%20you%20avoid%20spam%20and%20stay%20safe.
index.js:53 Uncaught (in promise) TypeError: Cannot read property 'fillingData' of undefined
    at index.js:53
    at u (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at r (asyncToGenerator.js:3)
    at l (asyncToGenerator.js:25)

**Comment by NathanLeadill** [comment]
Licence has expired for the live chat or something. Looks like an internal server error too tbh.

**Comment by nathanwatkinstemplar** [comment]
I've sorted Live chat licence

**Comment by nathanwatkinstemplar** [comment]
This is me going through and sending to Merchant 

https://share.vidyard.com/watch/cZ7iRrm3uX9M7dngcYbqqY?

The email was sent to Will who followed through on a video for send to merchant side and will comment here

**Comment by WilliamTemplar** [comment]
https://user-images.githubusercontent.com/83643714/127840378-5e60d820-6e69-4aae-82cf-e525e6b1d9b3.mov
