### ISSUE TITLE
Urgent: Not allowing submission of application

### ISSUE THREAD

**Issue by nathanwatkinstemplar** [Templar-Payments/Templar_Payments_BugTracking#120]
https://share.vidyard.com/watch/kk3JEcw5rioC6V6vAnnRXP?

**Comment by WilliamTemplar** [comment]
I get a continuous loading screen when I press submit but dont get the 500 error

https://user-images.githubusercontent.com/83643714/127834885-3bb6a113-dfa1-4f20-a9b9-879542e23087.mov

**Comment by NathanLeadill** [comment]
Test on localhost check the backend see whats happening

**Comment by nathanwatkinstemplar** [comment]
Fixed
