### ISSUE TITLE
Create a new application issue

### ISSUE THREAD

**Issue by jubisha** [Templar-Payments/Templar_Payments_BugTracking#14]
USer name - yiser27090@eyeremind.com
Paswd - 123

Steps to reproduce - 
1) Complete the registeration
2) Login with the registered email, go to create application and enter the company details, number
3) hit search
4) hit next, it will stop there and will not allow u to proceed. 

Please see below screenshot 

<img width="1312" alt="Screenshot 2021-07-16 at 6 30 40 PM" src="https://user-images.githubusercontent.com/56086942/125952054-1c87d866-1427-4b12-ab00-f50dc771a15c.png">
<img width="1390" alt="Screenshot 2021-07-16 at 6 30 50 PM" src="https://user-images.githubusercontent.com/56086942/125952081-ad4bf270-9aa2-4bfa-bb79-391a97354233.png">

**Comment by NathanLeadill** [comment]
Possible hotfix for 0.91
