### ISSUE TITLE
No validations on Send to Merchant page for email 

### ISSUE THREAD

**Issue by jubisha** [Templar-Payments/Templar_Payments_BugTracking#15]
USer name - yiser27090@eyeremind.com
Paswd - 123

Steps to produce :

No validations on email
It accepts incorrect email 

Also, if i enter a valid email and hit send link, i dont get any email on the email id

<img width="1079" alt="Screenshot 2021-07-16 at 9 13 56 PM" src="https://user-images.githubusercontent.com/56086942/125974068-9d71d0d9-cd8f-49b5-8ad2-898e7b2eb595.png">

**Comment by NathanLeadill** [comment]
Fixed
