### ISSUE TITLE
No Delete Button in Doc section in User settings

### ISSUE THREAD

**Issue by jubisha** [Templar-Payments/Templar_Payments_BugTracking#16]
USer name - yiser27090@eyeremind.com
Paswd - 123

Steps to produce :

In user settings , document section has no delete button if in case user wants to delete the docs how wud they del? 

<img width="1032" alt="Screenshot 2021-07-16 at 9 27 34 PM" src="https://user-images.githubusercontent.com/56086942/125975764-b05da3d3-c86f-4df0-b92d-34368c92a5b7.png">

**Comment by NathanLeadill** [comment]
This isn't implemented yet
