### ISSUE TITLE
Security Section - No validations

### ISSUE THREAD

**Issue by jubisha** [Templar-Payments/Templar_Payments_BugTracking#17]
USer name - yiser27090@eyeremind.com
Paswd - 123

Steps to produce :

if i dont enter the old paswd it allows me to proceed, 
Likewise if i dont enter the new paswd and confirm paswd it proceeds rather it should stop me there asking the user to input the paswd for all the 3 fields. 

![Uploading Screenshot 2021-07-16 at 9.29.24 PM.png…]()

**Comment by NathanLeadill** [comment]
Fixed going out in 0.92
