### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by jubisha** [Templar-Payments/Templar_Payments_BugTracking#18]
USer name - yiser27090@eyeremind.com
Paswd - 123

Steps to produce :

2 factor authentication accepts any incorrect value 
also if i dont enter the value in the field it does not throw any validation message stating to enter the code and simply closes the box

<img width="1055" alt="Screenshot 2021-07-16 at 9 31 32 PM" src="https://user-images.githubusercontent.com/56086942/125976306-53dd395b-8293-4d49-bb57-2a423e193408.png">

**Comment by NathanLeadill** [comment]
<img width="640" alt="Screenshot 2021-07-16 at 17 12 23" src="https://user-images.githubusercontent.com/17186852/125977503-298607fa-2f99-41c8-acae-d64691a9bf82.png">
Fixed with 0.92
