### ISSUE TITLE
Add User Issue 

### ISSUE THREAD

**Issue by jubisha** [Templar-Payments/Templar_Payments_BugTracking#19]
USer name - yiser27090@eyeremind.com
Paswd - 123

Steps to produce :

After creating the application go to admin area, select Add user, the new user u add doesn't show up in the records below  meaning it does not get added. 

<img width="1075" alt="Screenshot 2021-07-16 at 9 43 50 PM" src="https://user-images.githubusercontent.com/56086942/125977974-8f05b8ca-018a-4ba6-980f-5f0038557b8b.png">
<img width="1263" alt="Screenshot 2021-07-16 at 9 43 57 PM" src="https://user-images.githubusercontent.com/56086942/125977999-e79e741c-93cd-482f-bf9b-7ab38553a79f.png">

**Comment by NathanLeadill** [comment]
Fixed
