### ISSUE TITLE
Delete Record || Admin area

### ISSUE THREAD

**Issue by jubisha** [Templar-Payments/Templar_Payments_BugTracking#20]
USer name - yiser27090@eyeremind.com
Paswd - 123

Steps to produce :

After creating the application goto admin area, users and try deleting the record, delete throws error
rather it should delete the record and should thw a pop up saying "Are u sure u want to delete the record" if yes it should delete it and say "You have successfully deleted the record"

<img width="1011" alt="Screenshot 2021-07-16 at 9 49 58 PM" src="https://user-images.githubusercontent.com/56086942/125978539-17493568-0693-4384-9386-eff1c627aebd.png">
<img width="1422" alt="Screenshot 2021-07-16 at 9 36 46 PM" src="https://user-images.githubusercontent.com/56086942/125978574-d15422d4-022c-4652-a391-cd4c300b7a85.png">

**Comment by NathanLeadill** [comment]
Done
