### ISSUE TITLE
Delete - Addd acquirer  

### ISSUE THREAD

**Issue by jubisha** [Templar-Payments/Templar_Payments_BugTracking#21]
USer name - yiser27090@eyeremind.com
Paswd - 123

Steps to produce :

After creating the application goto admin area, users settings, add acquirer, after adding the acquirer try deleting it , 
it does nothing
rather it should delete the acquirer and should throw a pop up saying "Are u sure u want to delete the acquirer" if yes it should delete it and say "You have successfully deleted the acquirer"

<img width="1436" alt="Screenshot 2021-07-16 at 10 00 21 PM" src="https://user-images.githubusercontent.com/56086942/125979983-ba2f2da5-31cb-4e6d-9b76-498fb24ece25.png">

**Comment by NathanLeadill** [comment]
Fixed
