### ISSUE TITLE
Home icon

### ISSUE THREAD

**Issue by jubisha** [Templar-Payments/Templar_Payments_BugTracking#22]
On clicking the home icon of templar it should take u to the home page, Underlined in pink

<img width="1305" alt="Screenshot 2021-07-16 at 10 15 31 PM" src="https://user-images.githubusercontent.com/56086942/125981625-cc6fc000-7023-4c80-955c-f99c551c2891.png">

**Comment by NathanLeadill** [comment]
Fixed
