### ISSUE TITLE
User settings || Change email in general section 

### ISSUE THREAD

**Issue by jubisha** [Templar-Payments/Templar_Payments_BugTracking#23]
Goto User settings -> general, modify email it throws error as shown below

Initial email : pirete6758@ovooovo.com
paswd : 123

Change to email : pirete6758@ooovo.com

throws error 

<img width="1084" alt="Screenshot 2021-07-16 at 10 26 25 PM" src="https://user-images.githubusercontent.com/56086942/125982951-da46db3b-ecdf-40f3-b577-ba4786fbad9b.png">

**Comment by NathanLeadill** [comment]
@jubisha This means you need to re-login, it's an unhandled error, i'm working on adding a real message there.
