### ISSUE TITLE
Admin area 

### ISSUE THREAD

**Issue by jubisha** [Templar-Payments/Templar_Payments_BugTracking#24]
Email - pirete6758@ovooovo.com

paswd - 123

login with the email above
go to settings and click to admin area, it does nothing

<img width="1248" alt="Screenshot 2021-07-16 at 10 36 03 PM" src="https://user-images.githubusercontent.com/56086942/125984028-5a022438-43ae-4ef4-94ff-9106b72c813a.png">
<img width="1152" alt="Screenshot 2021-07-16 at 10 36 17 PM" src="https://user-images.githubusercontent.com/56086942/125984068-41c55226-5c0c-4e6e-9fa1-32f00abfe87c.png">

**Comment by NathanLeadill** [comment]
<img width="512" alt="Screenshot 2021-07-19 at 10 01 58" src="https://user-images.githubusercontent.com/17186852/126133583-d1bca269-1ec2-4625-90cf-10701a0633d5.png">

https://user-images.githubusercontent.com/17186852/126133610-520dce10-cbe1-4078-8749-221b22ba96ed.mov


https://user-images.githubusercontent.com/17186852/126133751-6487f1e8-6754-4762-8d51-4bd938467894.mov

Logical that this user cannot access the admin area as they are simply just a trial account member and so do not have access to the admin area part of the website. I have removed that button for non admin users
<img width="236" alt="Screenshot 2021-07-19 at 10 05 11" src="https://user-images.githubusercontent.com/17186852/126134042-1551a81b-76ac-470b-ab63-d962378d7e10.png">
