### ISSUE TITLE
Introduction Page before Tell us about you

### ISSUE THREAD

**Issue by nathanwatkinstemplar** [Templar-Payments/Templar_Payments_BugTracking#26]
Content above: May require a new screen design as 1 which is an introduction page similar to get started? Either that or the below text somewhere. 

Welcome to Templar Payments. 

The following information is required to set up your account with Templar Payment's Full Access BETA product. 

Welcome to Templar Payments. 

The following information is required to set up your account with Templar Payment's Full Access BETA product. 

Free Trial

If you do not wish to fill in this information and simply wish to process, up to 5 applications completely free of charge. Please select ‘Skip setup’ below. 

You are able to upgrade (or book a demo walkthrough) at any point during your free trial period

Full Access

If you’re here to set up your account, please follow the steps closely. If at any point you get stuck, you can access our resource centre via this link or talk to a Templar team member via the Live chat widget below.

*Your card will be charged for a setup fee (you can select either Monthly or Yearly) and will then be charged every 5 days to cover the cost of processing applications (unless you decide to purchase application credits upfront)

**Comment by NathanLeadill** [comment]
@nathanwatkinstemplar Extra stuff, wasn't in original spec. Need a design and another developer to do this
