### ISSUE TITLE
Modify profile settings

### ISSUE THREAD

**Issue by nathanwatkinstemplar** [Templar-Payments/Templar_Payments_BugTracking#29]
![Profile Page](https://user-images.githubusercontent.com/80484503/126034481-b4404d89-2246-4278-9fc3-54f1c5b47d5e.PNG)

When modifying profile page it kicks out a 401 error after the pop-up asking if you're sure you wish to modify them

**Comment by NathanLeadill** [comment]
<img width="368" alt="Screenshot 2021-07-19 at 10 29 56" src="https://user-images.githubusercontent.com/17186852/126137953-0a3240fd-c588-415b-a36b-9e96280b689d.png">
Just a CORS error fixed.
