### ISSUE TITLE
Field mapping errors

### ISSUE THREAD

**Issue by nathanwatkinstemplar** [Templar-Payments/Templar_Payments_BugTracking#30]
Basic company information

Company name isn't pulling through

Extra Stuff

Company Domain, PCI DSS certification, Micro enterprise not pulling through

Persons with Significant control

Percentage control not pulling through

**Comment by NathanLeadill** [comment]
<img width="343" alt="Screenshot 2021-07-19 at 13 54 20" src="https://user-images.githubusercontent.com/17186852/126162725-86ebd407-2e14-4798-87d6-6dff2d312162.png">
<img width="226" alt="Screenshot 2021-07-19 at 13 54 41" src="https://user-images.githubusercontent.com/17186852/126162774-b2687db1-efe8-4a34-a2c2-6f969f04664c.png">

I've got everything but PCI and licence required. Working on them

**Comment by NathanLeadill** [comment]
Fixed
