### ISSUE TITLE
Admin Setup - Skip 

### ISSUE THREAD

**Issue by nathanwatkinstemplar** [Templar-Payments/Templar_Payments_BugTracking#32]
Just not skip[ping vid here

https://share.vidyard.com/watch/w81g5TSQmSbk9FbttLYfx9?

**Comment by NathanLeadill** [comment]
https://user-images.githubusercontent.com/17186852/126134744-859473a7-a5e3-4805-9e2b-44a0d3176f76.mov

Seems to be working i'm assuming a token error?
