### ISSUE TITLE
Send link to merchant

### ISSUE THREAD

**Issue by nathanwatkinstemplar** [Templar-Payments/Templar_Payments_BugTracking#33]
I am getting an Error:  Request failed with Status code 500 when I try and open the link.

Can we also try and clean up how long the URL's are on the email? Just a small thing

**Comment by NathanLeadill** [comment]
The long URL's are a product of us passing info into the URL, we can maybe build a a tag so it doesn't look long on the email @nathanwatkinstemplar

**Comment by NathanLeadill** [comment]
Fixed
