### ISSUE TITLE
Admin area: Error when adding new user

### ISSUE THREAD

**Issue by nathanwatkinstemplar** [Templar-Payments/Templar_Payments_BugTracking#46]
https://share.vidyard.com/watch/bG2CY8BsLo5mUVVUd1jDyx?

**Comment by NathanLeadill** [comment]
<img width="737" alt="Screenshot 2021-07-19 at 23 55 45" src="https://user-images.githubusercontent.com/17186852/126237813-96c0d61d-f1f3-4302-a917-4ead6fd0bf28.png">
Looks like your org isn't setup correctly i'll look into this tomorrow
