### ISSUE TITLE
No Logout Button on the page

### ISSUE THREAD

**Issue by jubisha** [Templar-Payments/Templar_Payments_BugTracking#5]
There should be a logout button on the page, if user no longer want to access the application , they should have an ability to logout and start the application again,. 
<img width="1440" alt="Screenshot 2021-07-14 at 4 38 46 PM" src="https://user-images.githubusercontent.com/56086942/125612465-de8fe58a-8899-43ec-927c-2bceac4971cc.png">

**Comment by NathanLeadill** [comment]
Why would they log out at this stage?

**Comment by jubisha** [comment]
Probably good to have a log out button if one wants to log out and do not want to proceed with filling in the data

**Comment by jubisha** [comment]
Also, if i start to setup my details and if then i want to logout and login with the already registered email, then it should have a logout button so that i can logout. do you now agree?
