### ISSUE TITLE
Company Name not parsing from initially entering it 

### ISSUE THREAD

**Issue by nathanwatkinstemplar** [Templar-Payments/Templar_Payments_BugTracking#52]
When you enter the company name into the search function, it isn't filtering through to the Basic company information section on check and send

**Comment by NathanLeadill** [comment]
This is a known bug just don't have the effort to fix it one for @WilliamTemplar

**Comment by nathanwatkinstemplar** [comment]
With Will

**Comment by WilliamTemplar** [comment]
Completed and PR made
