### ISSUE TITLE
Big Ticket: Send link to Merchant journey

### ISSUE THREAD

**Issue by nathanwatkinstemplar** [Templar-Payments/Templar_Payments_BugTracking#54]
It kicks out a few bugs during this process. I recorded a 6 mins video of them. Leadill if you can look over it, and we can have some back and forth and then split into smaller bug fixes?

https://share.vidyard.com/watch/ina8noRRvDthEVjtSDwggR?

**Comment by NathanLeadill** [comment]
Spoke to you, need to stop users making errors :P
