### ISSUE TITLE
Cant progress past upload documents after refreshing

### ISSUE THREAD

**Issue by WilliamTemplar** [Templar-Payments/Templar_Payments_BugTracking#57]

**Comment by WilliamTemplar** [comment]
https://user-images.githubusercontent.com/83643714/126527897-b9231c7a-ef2f-44e0-860b-d54a59d00ddd.mov

**Comment by nathanwatkinstemplar** [comment]
This is related to an issue on the previous page, will says he has done the previous issue and is waiting for Leadill to merge that in so he can move onto this one

**Comment by WilliamTemplar** [comment]
Completed and PR made on feature/refreshError
