### ISSUE TITLE
Text change: Change legal document to Documents in the Document centre

### ISSUE THREAD

**Issue by nathanwatkinstemplar** [Templar-Payments/Templar_Payments_BugTracking#62]

**Comment by WilliamTemplar** [comment]
PR made, just checking that this is correct
<img width="906" alt="Screenshot 2021-07-22 at 09 39 36" src="https://user-images.githubusercontent.com/83643714/126611993-61903623-74b2-4526-8c67-c1e523be249a.png">

**Comment by nathanwatkinstemplar** [comment]
Yeah correct :-)
