### ISSUE TITLE
Messaging Center 

### ISSUE THREAD

**Issue by jubisha** [Templar-Payments/Templar_Payments_BugTracking#65]
Username - pirete6758@ovooovo.com
Paswd - 123

Go to messaging center,
do not write anything in the messaging box
just hit send 
it re-sends the date and time as text again and again, please see the attach screenshot. 

I would suggest unless user writes in the text in the textbox or msg box the send button should be disabled. 

![Uploading Screenshot 2021-07-22 at 3.13.46 PM.png…]()

**Comment by WilliamTemplar** [comment]
Completed and PR made
