### ISSUE TITLE
Messaging Center - Doc attach

### ISSUE THREAD

**Issue by jubisha** [Templar-Payments/Templar_Payments_BugTracking#66]
Username - pirete6758@ovooovo.com

Paswd - 123

when you go to messaging center and attach the doc and hit send, no doc is attached and sent in the message rather it sends the date and time 
<img width="1355" alt="Screenshot 2021-07-22 at 3 19 05 PM" src="https://user-images.githubusercontent.com/56086942/126620636-6024d437-5df5-4246-be2d-62d9cc1a352e.png">

**Comment by NathanLeadill** [comment]
Done
