### ISSUE TITLE
Sign up to gateway Beta

### ISSUE THREAD

**Issue by jubisha** [Templar-Payments/Templar_Payments_BugTracking#69]
User Name - lomob90686@britted.com
paswd - 123

When you hit the "Sign up to gateway beta" it throws 404

Please see screenshot below

<img width="798" alt="Screenshot 2021-07-22 at 4 46 41 PM" src="https://user-images.githubusercontent.com/56086942/126631361-db3eba6d-b69d-4c8b-906f-a0d10b9ce05b.png">
<img width="1090" alt="Screenshot 2021-07-22 at 4 46 32 PM" src="https://user-images.githubusercontent.com/56086942/126631371-e8544a75-06f2-4a25-ac7a-66db520194c0.png">

**Comment by nathanwatkinstemplar** [comment]
This is a change in workflow on Spells side that Watkins is aware of

**Comment by NathanLeadill** [comment]
Temp removal. Closed and removed
