### ISSUE TITLE
Add Subuser - No validations

### ISSUE THREAD

**Issue by jubisha** [Templar-Payments/Templar_Payments_BugTracking#7]
Accepts incorrect email format 
Accepts single digit name and last name

there should be validation in place. 

<img width="1072" alt="Screenshot 2021-07-14 at 4 58 08 PM" src="https://user-images.githubusercontent.com/56086942/125614781-b211a81f-e6a3-47ee-9545-c7efd2b359a6.png">
<img width="1392" alt="Screenshot 2021-07-14 at 4 58 19 PM" src="https://user-images.githubusercontent.com/56086942/125614804-250d34b6-97d9-45e7-a50d-349a63fd33c9.png">

**Comment by NathanLeadill** [comment]
Fixed, going up with 0.823

**Comment by NathanLeadill** [comment]
Fixed
