### ISSUE TITLE
Enhancement: Can we show number of credits remaining in user settings?

### ISSUE THREAD

**Issue by nathanwatkinstemplar** [Templar-Payments/Templar_Payments_BugTracking#71]
Thinking in General under Profile picture, we could have  Free Trial: Credits remaining X

**Comment by NathanLeadill** [comment]
<img width="197" alt="Screenshot 2021-07-23 at 19 04 42" src="https://user-images.githubusercontent.com/17186852/126823132-d552d432-3d78-4e6c-9ecf-d7bd38b1e0c5.png">
Done
