### ISSUE TITLE
Create app page - After a failed logon, you can skip to next page without completing inputs

### ISSUE THREAD

**Issue by WilliamTemplar** [Templar-Payments/Templar_Payments_BugTracking#82]
Also opens "Add person" swal

https://user-images.githubusercontent.com/83643714/126962900-690eb03a-99f6-4877-9ab3-faf45bdc1f1b.mov

**Comment by NathanLeadill** [comment]
Add a check if that's failed then looks easy enough from a network request @WilliamTemplar

**Comment by WilliamTemplar** [comment]
Completed and PR made 

https://user-images.githubusercontent.com/83643714/127143807-9e659fc1-bf4c-47e0-bc3c-18bf21dabff1.mov
