### ISSUE TITLE
Separate chat channel for GR8PAy not opening upon submission

### ISSUE THREAD

**Issue by nathanwatkinstemplar** [Templar-Payments/Templar_Payments_BugTracking#83]
A separate chat channel should be opened (separate to the bank applications) which adds automatically onboarding@gr8pay.com to the chat thread so that they can send a quote to the ISO.

**Comment by NathanLeadill** [comment]
Yah this was the bug, so i've removed it until I have time to fix it @nathanwatkinstemplar

**Comment by nathanwatkinstemplar** [comment]
No worries, let me know once done and I can do the full onboarding video

**Comment by NathanLeadill** [comment]
<img width="730" alt="Screenshot 2021-07-27 at 13 45 32" src="https://user-images.githubusercontent.com/17186852/127155792-8441e176-4a2d-4c00-ab45-9ba118792df9.png">
Done from bed! @nathanwatkinstemplar  will push later this evening
