### ISSUE TITLE
Button for changing user profile pic

### ISSUE THREAD

**Issue by WilliamTemplar** [Templar-Payments/Templar_Payments_BugTracking#85]

**Comment by WilliamTemplar** [comment]
Completed and PR made

https://user-images.githubusercontent.com/83643714/127014989-a1983f9c-4c0d-49bb-8c06-aafe5601524e.mov

**Comment by NathanLeadill** [comment]
Probably a better version than what i've made we need to unpick this though because i have another version on live rn :P @WilliamTemplar
