### ISSUE TITLE
Format date & time

### ISSUE THREAD

**Issue by WilliamTemplar** [Templar-Payments/Templar_Payments_BugTracking#88]
On the tables the date and time is set out like "2021-07-28T11:57:22.433Z" which is pretty difficult to read. Should probably look more like "2021-07-28 11:57:22".
Also add a indication of date format in title e.g. (YYYY-MM-DD)

**Comment by nathanwatkinstemplar** [comment]
Yeah, agreed :-)

**Comment by WilliamTemplar** [comment]
Completed and PR made on feature/formatDate
