### ISSUE TITLE
Send Link Issue 

### ISSUE THREAD

**Issue by jubisha** [Templar-Payments/Templar_Payments_BugTracking#9]
On click send link it does nothing 
It doesn't seems to be working. 

<img width="1418" alt="Screenshot 2021-07-14 at 8 08 00 PM" src="https://user-images.githubusercontent.com/56086942/125641108-e491690d-d150-4518-bae7-a71c60f87d3d.png">

Send link is still not working

**Comment by NathanLeadill** [comment]
Fixed, going out in 0.823

**Comment by jubisha** [comment]
Send link is still not working

**Comment by NathanLeadill** [comment]
These fixes aren't pushed yet @jubisha
