### ISSUE TITLE
Need spacing of text on check details section

### ISSUE THREAD

**Issue by WilliamTemplar** [Templar-Payments/Templar_Payments_BugTracking#91]
The titles and the user inputs aren't separate so sometimes appears like one big sentence

<img width="709" alt="Screenshot 2021-07-28 at 14 49 57" src="https://user-images.githubusercontent.com/83643714/127337062-8d03755b-2944-40e0-85b9-465868d8ad34.png">
<img width="656" alt="Screenshot 2021-07-28 at 14 51 14" src="https://user-images.githubusercontent.com/83643714/127337087-22ecebf0-5887-442f-818d-c7f8aa9f456b.png">

**Comment by nathanwatkinstemplar** [comment]
Agreed :-)

**Comment by WilliamTemplar** [comment]
Completed and PR made

<img width="903" alt="Screenshot 2021-07-30 at 14 21 06" src="https://user-images.githubusercontent.com/83643714/127659046-a17c11f8-2597-400a-8f5a-89af84829c3b.png">
