### ISSUE TITLE
Remove download icon on upload documents?

### ISSUE THREAD

**Issue by WilliamTemplar** [Templar-Payments/Templar_Payments_BugTracking#92]
The download icon appears when you upload a document but has no functionality. May need removing

<img width="174" alt="Screenshot 2021-07-28 at 14 45 46" src="https://user-images.githubusercontent.com/83643714/127337579-5c18d0c4-f22c-4664-a726-db8cc3d68ce9.png">

**Comment by nathanwatkinstemplar** [comment]
Agreed :-)

**Comment by WilliamTemplar** [comment]
Completed and PR made on feature/minorChanges
