### ISSUE TITLE
Minor text change: Stuff extracted

### ISSUE THREAD

**Issue by WilliamTemplar** [Templar-Payments/Templar_Payments_BugTracking#93]
May be better to change to something more formal like "Information extracted" or "Data extracted"
<img width="454" alt="Screenshot 2021-07-28 at 14 45 04" src="https://user-images.githubusercontent.com/83643714/127338157-a3e77cc1-595e-4c19-9199-c10e603bfbc4.png">

**Comment by nathanwatkinstemplar** [comment]
Yeah, change to 'Information extracted'

**Comment by WilliamTemplar** [comment]
Completed and PR made on feature/minorChanges
