### ISSUE TITLE
Create application breaks when selecting 3 banks

### ISSUE THREAD

**Issue by WilliamTemplar** [Templar-Payments/Templar_Payments_BugTracking#95]
When selecting banks, if you select 3 then you are unable to select any more banks (which is correct for trial version) but doesn't allow you to deselect any of the 3 banks

https://user-images.githubusercontent.com/83643714/127340599-de7d71dc-6dfc-4fca-b1f8-baf934d65886.mov

**Comment by NathanLeadill** [comment]
Just needs a check in the if statement

**Comment by WilliamTemplar** [comment]
Completed and PR made 

https://user-images.githubusercontent.com/83643714/127666164-ae43e899-520b-4f30-a990-c6adba162139.mov
