### ISSUE TITLE
tell us about you Validation 

### ISSUE THREAD

**Issue by jubisha** [Templar-Payments/Templar_Payments_BugTracking#99]
User name - kojoye1977@biohorta.com
Paswd - 123

After entering all the correct data it still says validation missing

Suggestion 

I would advise if we enter the incorrect ph number and the correct Domain name then it should display a validation saying "Phone number is incorrect" or "field name is incorrect " so that the user know in which field to correct the data. Rather than having generic message, we should have a field level validations. 

<img width="1423" alt="Screenshot 2021-07-29 at 4 57 33 PM" src="https://user-images.githubusercontent.com/56086942/127484549-c6e3cac4-ce7d-4e49-b71c-828c2fa8a349.png">

**Comment by NathanLeadill** [comment]
Closing this i've said before it's a V3 thing.
